### ISSUE TITLE
Create data structures

### ISSUE THREAD

**Issue by tusty53** [tusty53/electrihive#1]
Create classes for a single node, whole graph, power plant, network and solution.

**Comment by tusty53** [comment]
NetworkX seems to be good enough for the purpose of basic structures. However, we have to decide whether we want to create a set of power plants, each with a reference to a node is is to be built on or keep power plants as an attribute of the node.
Also, it may be a good idea to create a hierarchy for the structures in order not to keep redundant data. My first idea would be to represent solution as a set of networks, with each network containing a set of nodes, set of edges and a power plant pointing to a certain node. This way, we can easily check conditions of the proper solution.

**Comment by rychuhardy** [comment]
I agree with your idea for representing solutions. We can create subgraphs out of original graph using this function:

https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.Graph.subgraph.html

Therefore I reckon that the solution should be represented as a list of pairs where each pair consists of a graph and power plant structure.

Then the power plant structure can hold reference to node and have some integer value (cost). 

I don't think we should worry about redundancy now as our graphs won't be larger than 10^6 nodes, so having bidirectional references is ok.
