### ISSUE TITLE
Create and read configuration file

### ISSUE THREAD

**Issue by tusty53** [tusty53/electrihive#2]
Create configuration file schema (xml, json, plain text file etc.).
Create separate python configuration file to include in project.
Create module for reading configuration into that file.

**Comment by rychuhardy** [comment]
Is this a program configuration or an algorithm configuration? I think we can pass algorithm configuration via GUI and this would solve points 1 and 2 from https://github.com/tusty53/electrihive/issues/9

**Comment by tusty53** [comment]
I meant it as algorithm configuration -  I don't know about any program configuration that we need so far. Making GUI for config sounds great.

**Comment by tusty53** [comment]
Closed by #14
